// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Message.proto</summary>
public static partial class MessageReflection {

  #region Descriptor
  /// <summary>File descriptor for Message.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1NZXNzYWdlLnByb3RvIrECCghQcm90b2NvbBILCgNrZXkYASABKAkSJAoE",
          "dHlwZRgCIAEoDjIWLlByb3RvY29sLlByb3RvY29sVHlwZRIMCgRuYW1lGAMg",
          "ASgJEhAKCHJvb21fa2V5GAQgASgJEgsKA21zZxgFIAEoCRITCgtiZWdpbl9w",
          "b2ludBgGIAEoARIRCgllbmRfcG9pbnQYByABKAESEAoIcGVuX3NpemUYCCAB",
          "KAUSDQoFY29sb3IYCSABKAUifAoMUHJvdG9jb2xUeXBlEgkKBUxPR0lOEAAS",
          "DwoLQ1JFQVRFX1JPT00QARINCglKT0lOX1JPT00QAhIOCgpMRUFWRV9ST09N",
          "EAMSCAoEQ0hBVBAEEg4KCkdBTUVfQkVHSU4QBRIMCghHQU1FX0VORBAGEgkK",
          "BVBBSU5UEAdiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Protocol), global::Protocol.Parser, new[]{ "Key", "Type", "Name", "RoomKey", "Msg", "BeginPoint", "EndPoint", "PenSize", "Color" }, null, new[]{ typeof(global::Protocol.Types.ProtocolType) }, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Protocol : pb::IMessage<Protocol> {
  private static readonly pb::MessageParser<Protocol> _parser = new pb::MessageParser<Protocol>(() => new Protocol());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Protocol> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Protocol() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Protocol(Protocol other) : this() {
    key_ = other.key_;
    type_ = other.type_;
    name_ = other.name_;
    roomKey_ = other.roomKey_;
    msg_ = other.msg_;
    beginPoint_ = other.beginPoint_;
    endPoint_ = other.endPoint_;
    penSize_ = other.penSize_;
    color_ = other.color_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Protocol Clone() {
    return new Protocol(this);
  }

  /// <summary>Field number for the "key" field.</summary>
  public const int KeyFieldNumber = 1;
  private string key_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Key {
    get { return key_; }
    set {
      key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 2;
  private global::Protocol.Types.ProtocolType type_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Protocol.Types.ProtocolType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 3;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "room_key" field.</summary>
  public const int RoomKeyFieldNumber = 4;
  private string roomKey_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string RoomKey {
    get { return roomKey_; }
    set {
      roomKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "msg" field.</summary>
  public const int MsgFieldNumber = 5;
  private string msg_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Msg {
    get { return msg_; }
    set {
      msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "begin_point" field.</summary>
  public const int BeginPointFieldNumber = 6;
  private double beginPoint_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public double BeginPoint {
    get { return beginPoint_; }
    set {
      beginPoint_ = value;
    }
  }

  /// <summary>Field number for the "end_point" field.</summary>
  public const int EndPointFieldNumber = 7;
  private double endPoint_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public double EndPoint {
    get { return endPoint_; }
    set {
      endPoint_ = value;
    }
  }

  /// <summary>Field number for the "pen_size" field.</summary>
  public const int PenSizeFieldNumber = 8;
  private int penSize_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int PenSize {
    get { return penSize_; }
    set {
      penSize_ = value;
    }
  }

  /// <summary>Field number for the "color" field.</summary>
  public const int ColorFieldNumber = 9;
  private int color_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Color {
    get { return color_; }
    set {
      color_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Protocol);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Protocol other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Key != other.Key) return false;
    if (Type != other.Type) return false;
    if (Name != other.Name) return false;
    if (RoomKey != other.RoomKey) return false;
    if (Msg != other.Msg) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(BeginPoint, other.BeginPoint)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(EndPoint, other.EndPoint)) return false;
    if (PenSize != other.PenSize) return false;
    if (Color != other.Color) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Key.Length != 0) hash ^= Key.GetHashCode();
    if (Type != 0) hash ^= Type.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (RoomKey.Length != 0) hash ^= RoomKey.GetHashCode();
    if (Msg.Length != 0) hash ^= Msg.GetHashCode();
    if (BeginPoint != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(BeginPoint);
    if (EndPoint != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(EndPoint);
    if (PenSize != 0) hash ^= PenSize.GetHashCode();
    if (Color != 0) hash ^= Color.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Key.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Key);
    }
    if (Type != 0) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Type);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Name);
    }
    if (RoomKey.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(RoomKey);
    }
    if (Msg.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Msg);
    }
    if (BeginPoint != 0D) {
      output.WriteRawTag(49);
      output.WriteDouble(BeginPoint);
    }
    if (EndPoint != 0D) {
      output.WriteRawTag(57);
      output.WriteDouble(EndPoint);
    }
    if (PenSize != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(PenSize);
    }
    if (Color != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(Color);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Key.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
    }
    if (Type != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (RoomKey.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomKey);
    }
    if (Msg.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
    }
    if (BeginPoint != 0D) {
      size += 1 + 8;
    }
    if (EndPoint != 0D) {
      size += 1 + 8;
    }
    if (PenSize != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PenSize);
    }
    if (Color != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Color);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Protocol other) {
    if (other == null) {
      return;
    }
    if (other.Key.Length != 0) {
      Key = other.Key;
    }
    if (other.Type != 0) {
      Type = other.Type;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.RoomKey.Length != 0) {
      RoomKey = other.RoomKey;
    }
    if (other.Msg.Length != 0) {
      Msg = other.Msg;
    }
    if (other.BeginPoint != 0D) {
      BeginPoint = other.BeginPoint;
    }
    if (other.EndPoint != 0D) {
      EndPoint = other.EndPoint;
    }
    if (other.PenSize != 0) {
      PenSize = other.PenSize;
    }
    if (other.Color != 0) {
      Color = other.Color;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Key = input.ReadString();
          break;
        }
        case 16: {
          type_ = (global::Protocol.Types.ProtocolType) input.ReadEnum();
          break;
        }
        case 26: {
          Name = input.ReadString();
          break;
        }
        case 34: {
          RoomKey = input.ReadString();
          break;
        }
        case 42: {
          Msg = input.ReadString();
          break;
        }
        case 49: {
          BeginPoint = input.ReadDouble();
          break;
        }
        case 57: {
          EndPoint = input.ReadDouble();
          break;
        }
        case 64: {
          PenSize = input.ReadInt32();
          break;
        }
        case 72: {
          Color = input.ReadInt32();
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the Protocol message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum ProtocolType {
      [pbr::OriginalName("LOGIN")] Login = 0,
      [pbr::OriginalName("CREATE_ROOM")] CreateRoom = 1,
      [pbr::OriginalName("JOIN_ROOM")] JoinRoom = 2,
      [pbr::OriginalName("LEAVE_ROOM")] LeaveRoom = 3,
      [pbr::OriginalName("CHAT")] Chat = 4,
      [pbr::OriginalName("GAME_BEGIN")] GameBegin = 5,
      [pbr::OriginalName("GAME_END")] GameEnd = 6,
      [pbr::OriginalName("PAINT")] Paint = 7,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
